### ISSUE TITLE
[Decorator] [Tesla] using functions from "ModelS"

### ISSUE THREAD

**Issue by hasezoey** [SavjeeTutorials/typescript-design-patterns#2]
i have modified abstract Car to have an abstract function "hello"
```ts
abstract class Car{
    public description: string;

    public getDescription() : string{
        return this.description;
    };

    public abstract cost(): number;

    public abstract hello(): void;
}
```
Model S & X include them as
```ts
class ModelS extends Car{
    public description = "Model S";

    public cost(): number {
        return 73000;
    }

    public hello(): void {
        console.log("hello from ModelS");
    }
}
```
(i didnt modify anything from the decorators)

and at the end
```ts
let myTesla = new ModelS();
myTesla = new SmartAirSuspension(myTesla);
myTesla = new RearFacingSeats(myTesla);

console.log(myTesla.hello());
```
`console.log(myTesla.hello());` Errors because the two Decorators dont include a hello function, arnt they supposed to just extend the Model(S/X) (also include the functions from Model(S/X)?

**Comment by Savjee** [comment]
The problem here is that your classes `SmartAirSuspension` and `RearFacingSeats` don't have the `hello` method. 

When you run `myTesla.hello()` it will try to execute the `hello()` method on `RearFacingSeats` which probably doesn't have it!

**Comment by hasezoey** [comment]
> console.log(myTesla.hello()); Errors because the two Decorators dont include a hello function, arnt they supposed to just extend the Model(S/X) (also include the functions from Model(S/X)?

with that i meant, is it really necessary to implement all function from Model(S/X), instead of just overriding the functions that need to be changed?

**Comment by Savjee** [comment]
Yes, especially if you're using `abstract` methods! If you use regular methods they will be available on all subclasses as well. So you could include a generic `hello` method.

**Comment by hasezoey** [comment]
i dont know if this is the intention of the Decorator Pattern, but this is what i had in mind
https://gist.github.com/hasezoey/357b3d9c0528dfa885479302c4d63683
because yet, i could add functions without copy them to the other options too
